#!/bin/sh

echo "Is it moring? Please answer yes or no"
read timeofday

case "$timeofday" in
	yes) echo "Good Morning";;
	no)  echo "Good Afternoon";;
	y)   echo "Good Morning";;
	n)   echo "Good Afternoon";;
	*)   echo "Sorry, answer not recognized";;
esac


read timeofday

case $timeofday in
	yes | y | Yes | YES) echo "Good Morning";;
	n* | N*) 			 echo "Good Afternoon";;
	*) 					 echo "Sorry, answer not recognized";;
esac

read timeofday 

case "$timeofday" in 
	yes | y | Yes | YES)
		echo "Good Morning"
		echo "Up bright and early this moring"
		;;
	[nN]*)
		echo "Good Afternoon"
		;;
	*)
		echo "Sorry, answer not recognized"
		echo "Please answer yes or no"
		exit 1
		;;
esac


exit 0
